---
# Light group: hallway_small
#
# This light controls all the lights in small hallway behind the kitchen.
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: hallway_small
entities:
  - light.hallway_small_ceiling_spotlight_1
