---
# Light group: Living Room
#
# This light controls all the other lights in my living room
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: living_room
entities:
  - light.living_room_spotlight_1
  - light.living_room_spotlight_2
  - light.living_room_spotlight_3
  - light.living_room_spotlight_4
  - light.living_room_spotlight_5
  - light.living_room_spotlight_6
  - light.living_room_spotlight_7
  - light.living_room_spotlight_8
