---
# Light group: office_janneke
#
# This light controls all the other lights in Janneke's office
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: office_janneke
entities:
  - light.office_janneke_ceiling_spotlight_1
  - light.office_janneke_ceiling_spotlight_2
  - light.office_janneke_ceiling_spotlight_3
